#!/usr/bin/env bun
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const THEMES = [
  "ocean",
  "purple",
  "catppuccin",
  "dusk",
  "emerald",
  "ruby",
  "solar",
  "black",
  "shadcn",
  "vitepress",
  "aspen",
];

const FUMADOCS_UI_PACKAGE_PATH = fileURLToPath(import.meta.resolve("fumadocs-ui/package.json"));
const THEME_CSS_DIR = path.join(path.dirname(FUMADOCS_UI_PACKAGE_PATH), "css");
const OUTPUT = path.resolve(import.meta.dirname, "../web/generated/themes.css");

const extractVars = (block: string) => {
  return block
    .split("\n")
    .filter((line) => line.trim().startsWith("--"))
    .join("\n");
};

const chunks: string[] = ["/* auto-generated by scripts/generate-themes.ts */"];

for (const theme of THEMES) {
  const css = readFileSync(path.join(THEME_CSS_DIR, `${theme}.css`), "utf-8");

  // extract @theme { ... } block vars
  const themeMatch = css.match(/@theme\s*\{([\s\S]*?)\}/);
  const lightVars = themeMatch ? extractVars(themeMatch[1]) : "";

  // extract .dark { ... } block vars
  const darkMatch = css.match(/\.dark\s*\{([\s\S]*?)\}/);
  const darkVars = darkMatch ? extractVars(darkMatch[1]) : "";

  // extract extra rules like .dark body { ... }
  const extraRules: string[] = [];
  const bodyMatch = css.match(/\.dark\s+body\s*\{([\s\S]*?)\}/);
  if (bodyMatch) {
    extraRules.push(`.dark[data-theme="${theme}"] body {\n${bodyMatch[1]}\n}`);
  }

  let block = `/* ${theme} */\n`;
  if (lightVars) block += `[data-theme="${theme}"] {\n${lightVars}\n}\n`;
  if (darkVars) block += `.dark[data-theme="${theme}"] {\n${darkVars}\n}\n`;
  if (extraRules.length) block += extraRules.join("\n") + "\n";

  chunks.push(block);
}

writeFileSync(OUTPUT, chunks.join("\n"));
console.log(`generated ${THEMES.length} theme overrides`);
